name: CI

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: fpco/stack-build:lts-21.25
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Foma
        run: |
          apt-get update
          apt-get install -y --no-install-recommends foma libfoma-dev

      - name: Stack install
        run: stack install

      - name: Setup HLint
        uses: haskell-actions/hlint-setup@v2

      - name: Run HLint
        uses: haskell-actions/hlint-run@v2
        with:
          path: '["app","src","tests"]'
          fail-on: warning

      - name: Stack test
        run: stack test
